
CREATE TABLE PDBADMIN.SF_IN_CONTMAR_OT (
	ID INTEGER NULL,
	CONTAINER_NR VARCHAR2(100) NULL,
	DEPARTURE_DATE DATE NULL,
	BL VARCHAR2(100) NULL,
	EQUIPMENT VARCHAR2(100) NULL,
	POL VARCHAR2(100) NULL,
	PLD VARCHAR2(100) NULL,
	CUENTA_CENTRO_DE_COSTOS VARCHAR2(100) NULL,
	MA VARCHAR2(100) NULL,
	INTERCOM VARCHAR2(100) NULL
);


/
CREATE OR REPLACE PROCEDURE PDBADMIN.TO_CALL
IS
v_id NUMBER;
BEGIN
	
	SELECT id INTO v_id FROM SF_IN_CONTMAR_OT;
	dbms_output.put_line( v_id );
dbms_output.put_line('hi' );
END TO_CALL;
-------------------------------------------------


ALTER USER system QUOTA UNLIMITED ON USERS;


CREATE TABLE PDBADMIN.SF_IN_CONTMAR_OT (
	ID INTEGER NULL,
	CONTAINER_NR VARCHAR2(100) NULL,
	DEPARTURE_DATE DATE NULL,
	BL VARCHAR2(100) NULL,
	EQUIPMENT VARCHAR2(100) NULL,
	POL VARCHAR2(100) NULL,
	PLD VARCHAR2(100) NULL,
	CUENTA_CENTRO_DE_COSTOS VARCHAR2(100) NULL,
	MA VARCHAR2(100) NULL,
	INTERCOM VARCHAR2(100) NULL
);


	SELECT * FROM SF_IN_CONTMAR_OT;

DECLARE
ids NUMBER;
BEGIN
	ids := 0;
	PDBADMIN.TO_CALL(ids);
END;

DECLARE
ids NUMBER;
BEGIN
	ids := 0;
	PDBADMIN.VALIADTIONS(1, '1999.11.11', '12', '13', 'v_pol', 'v_pld', 'v_cuenta', 'v_ma', 'v_intercomunicador', ids);
END;


SELECT TO_CHAR(TO_DATE('1999.11.11','YYYY.MM.DD'),'YYYY/MM/DD') FROM DUAL;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD';

ALTER USER PDBADMIN  quota 100M on USERS;


ALTER USER SYSTEM quota unlimited on USERS;


GRANT CONNECT TO SYSTEM

GRANT RESOURCE TO  SYSTEM




BEGIN
	PDBADMIN.READ_FILES( 'excel.CSV');
END;

INSERT INTO PDBADMIN.SF_IN_CONTMAR_OT
(ID, CONTAINER_NR, DEPARTURE_DATE, BL, EQUIPMENT, POL, PLD, CUENTA_CENTRO_DE_COSTOS, MA, INTERCOM)
VALUES(1, '', '', '', '', '', '', '', '', '');


ALTER TABLE SF_IN_CONTMAR_OT ADD (
  CONSTRAINT sf_pk PRIMARY KEY (ID));

CREATE SEQUENCE SEQ_SF_IN_CONTMAR_OT START WITH 1;
--
ALTER USER system QUOTA UNLIMITED ON USERS;


CREATE TABLE PDBADMIN.SF_IN_CONTMAR_OT (
	ID INTEGER NULL,
	CONTAINER_NR VARCHAR2(100) NULL,
	DEPARTURE_DATE DATE NULL,
	BL VARCHAR2(100) NULL,
	EQUIPMENT VARCHAR2(100) NULL,
	POL VARCHAR2(100) NULL,
	PLD VARCHAR2(100) NULL,
	CUENTA_CENTRO_DE_COSTOS VARCHAR2(100) NULL,
	MA VARCHAR2(100) NULL,
	INTERCOM VARCHAR2(100) NULL
);


	SELECT * FROM SF_IN_CONTMAR_OT;

create or replace directory USER_DIR as 'C:\app';
grant read, write on directory USER_DIR to PDBADMIN;

BEGIN
	TO_CALL();
END;


DECLARE
	ids NUMBER;
BEGIN
	ids := 0;
	PDBADMIN.VALIADTIONS(1, '1999.11.11', '12', '13', 'v_pol', 'v_pld', 'v_cuenta', 'v_ma', 'v_intercomunicador', ids);
END;



ALTER USER SYSTEM  quota 100M on users;


ALTER USER SYSTEM quota unlimited on USERS;



create user vic identified by admin_password;

grant CONNECT TO PDBADMIN;




BEGIN
	PDBADMIN.READ_FILES( 'excel.CSV');
END;



------------------------------

DECLARE
      F UTL_FILE.FILE_TYPE;
      V_LINE VARCHAR2 (1000);     
      V_ENAME VARCHAR2(10);    
      V_DNAME VARCHAR2(14);
      CONTAINER_NR  VARCHAR2(100);
 	  DEPARTURE_DATE  DATE;
 	  EQUIPMENT VARCHAR2(100);
 	  BL  VARCHAR2(100);
 	  POL  VARCHAR2(100);
	  PLD  VARCHAR2(100);
	  CUENTA_CENTRO_DE_COSTOS  VARCHAR2(100);
	  MA  VARCHAR2(100);
	  INTERCOM VARCHAR2(100);
BEGIN
    F := UTL_FILE.FOPEN ('USER_DIR', 'aritimi.CSV', 'R');
    IF UTL_FILE.IS_OPEN(F) THEN
      LOOP
        BEGIN
          UTL_FILE.GET_LINE(F, V_LINE, 1000);
          IF V_LINE IS NULL THEN
            EXIT;
          END IF;
          CONTAINER_NR := REGEXP_SUBSTR(V_LINE, '[^,]+', 1, 1);
          DEPARTURE_DATE := REGEXP_SUBSTR(V_LINE, '[^,]+', 1, 2);
          BL := REGEXP_SUBSTR(V_LINE, '[^,]+', 1, 3);
          EQUIPMENT := REGEXP_SUBSTR(V_LINE, '[^,]+', 1, 4);
          POL := REGEXP_SUBSTR(V_LINE, '[^,]+', 1, 5);
          PLD := REGEXP_SUBSTR(V_LINE, '[^,]+', 1, 6);
          CUENTA_CENTRO_DE_COSTOS := REGEXP_SUBSTR(V_LINE, '[^,]+', 1, 7);
          MA := REGEXP_SUBSTR(V_LINE, '[^,]+', 1, 8);
          INTERCOM := REGEXP_SUBSTR(V_LINE, '[^,]+', 1, 9);
          INSERT PDBADMIN.SF_IN_CONTMAR_OT VALUES(CONTAINER_NR, DEPARTURE_DATE, BL, EQUIPMENT, POL, PLD, CUENTA_CENTRO_DE_COSTOS, MA, INTERCOM);
          COMMIT;        
          EXCEPTION
        	WHEN NO_DATA_FOUND THEN
          EXIT;
        END;
      END LOOP;
    END IF;
    UTL_FILE.FCLOSE(F);
  END;


 
 SELECT TO_CHAR(TO_DATE('11.11.1999','MM.DD.YYYY'),'YYYY/MM/DD') FROM DUAL;